name: cloud_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - python=3.8.1
  - xarray=0.15.0
  - dask=2.10.1
  - zarr=2.4.0
  - fsspec=0.6.2
  - s3fs=0.4.0
  - matplotlib=3.1.3
  - cartopy=0.17.0
  - intake=0.5.4
  - intake-esm=2019.12.13
  - intake-xarray=0.3.1


